### PR TITLE
Correct context name used in Spider scans

### PR DESCRIPTION
**Pull request by hesk**
Use evaluatedContextName for Spider Scan

### CODE REVIEW

**Comment by JordanGS** [comment]
@hesk great catch!

can you please update the commit message to bring it in line with the previous and future version history.

Change from:

```
Update ZAPDriver.java

Use evaluatedContextName in Spider Scan
```

to

```
Correct context name used in Spider scans

Use evaluatedContextName in Spider Scan API call.
```

and the title of the pull request would be just "Correct context name used in Spider scans"

I have changed the base branch of the merge to be development, rather than master.  You will have to rebase the branch (to get rid of the previous commits), can be done while amending the commit.

it might seem as redundancy but it looks better in the history and will be consistent with the pull request.

**Comment by hesk** [comment]
@JordanGS ok

**Comment by JordanGS** [comment]
@hesk your changes are in, thank you! You will see the fix within the next day or two. Investigating one other potential issue with the plugin which i may add into the the hotfix before releasing.

**Comment by JordanGS** [comment]
@hesk New released has been [published](https://github.com/jenkinsci/zap-plugin/releases/tag/zap-1.0.4). Should be available within 8 hour from this post, remember to click on update manage and press "Check Now" since Jenkins only updates once every 24 hours.

**Comment by hesk** [comment]
@JordanGS Great, will do.

**Pull request merged**
