### PR TITLE
Alert Filters: JENKINS-39985

### PR DESCRIPTION
**Pull request by tlenaic**
Added support for context Alert Filters

FIX [JENKINS-39985](https://issues.jenkins-ci.org/browse/JENKINS-39985)

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thanks!

**Comment by JordanGS** [comment]
@tlenaic Great work! Squashed and merged. I have some more ideas about how to make this feature more robust, if you're interested let me know.

**Comment by tlenaic** [comment]
Yes i'm.
i have also and idea in a corner of my head, how to manage alert filter file. (generate alert filter file from zap plugin report.)

**Comment by thc202** [comment]
FYI, the Alert Filters add-on will be changed to allow to import/export, to XML file, the filters defined in a context.

**Pull request merged**
